package models.user;

import models.ppt.ProjectPlanningTool;

import javax.persistence.*;

@Entity
@Table(name = "pptaccount")
public class PPTAccount {

	@SuppressWarnings("UnusedDeclaration") //generated by hibernate
	@Id
	@SequenceGenerator(name = "pptaccount_seq", sequenceName = "pptaccount_seq")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "pptaccount_seq")
	private Long id;

	@ManyToOne
	private ProjectPlanningTool ppt;

	private String pptUrl;

	@ManyToOne
	private User user;

	private String ppt_username;

	private String ppt_password;

}
