package models.user;

import models.ppt.ProjectPlanningTool;

import javax.persistence.*;

@Entity
@Table(name = "pptaccount")
public class PPTAccount {

	@SuppressWarnings("UnusedDeclaration") //generated by hibernate
	@Id
	@SequenceGenerator(name = "pptaccount_seq", sequenceName = "pptaccount_seq")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "pptaccount_seq")
	private Long id;

	@ManyToOne
	private ProjectPlanningTool ppt;

	private String pptUrl;

	@ManyToOne
	private User user;

	private String ppt_username;

	private String ppt_password;

	public Long getId() {
		return id;
	}

	public String getPptUrl() {
		return pptUrl;
	}

	public void setPptUrl(String pptUrl) {
		this.pptUrl = pptUrl;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getPpt_username() {
		return ppt_username;
	}

	public void setPpt_username(String ppt_username) {
		this.ppt_username = ppt_username;
	}

	public String getPpt_password() {
		return ppt_password;
	}

	public void setPpt_password(String ppt_password) {
		this.ppt_password = ppt_password;
	}
}
