package models.user;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;
import java.security.SecureRandom;

@Entity
@Table(name = "person")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class User {

	public static final SecureRandom SECURE_RANDOM = new SecureRandom();

	@SuppressWarnings("UnusedDeclaration") //generated by hibernate
	@Id
	@SequenceGenerator(name = "user_seq", sequenceName = "user_seq")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "user_seq")
	private Long id;

	private String name;

	@JsonIgnore
	private byte[] salt;

	@JsonIgnore
	private byte[] password_hash;

	public Long getId() {
		return id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public byte[] getPassword_hash() {
		return password_hash;
	}

	public void setPassword_hash(byte[] password_hash) {
		this.password_hash = password_hash;
	}

	public byte[] getSalt() {
		return salt;
	}

	public void initSalt() {
		salt = SECURE_RANDOM.generateSeed(20);
	}
}
