package models.task;

import javax.persistence.*;

@Entity
@Table(name = "tasktpropertyvalue")
public class TaskPropertyValue {

	@SuppressWarnings("UnusedDeclaration") //generated by hibernate
	@Id
	@SequenceGenerator(name = "tasktpropertyvalue_seq", sequenceName = "tasktpropertyvalue_seq")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "tasktpropertyvalue_seq")
	private Long id;

	@ManyToOne
	private TaskProperty property;

	private String value;

	public Long getId() {
		return id;
	}

	public TaskProperty getProperty() {
		return property;
	}

	public void setProperty(TaskProperty property) {
		this.property = property;
	}

	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}
}
