package models.task;

import javax.persistence.*;

@Entity
@Table(name = "taskproperty")
public class TaskProperty {
	@SuppressWarnings("UnusedDeclaration") //generated by hibernate
	@Id
	@SequenceGenerator(name = "taskproperty_seq", sequenceName = "taskproperty_seq")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "taskproperty_seq")
	private Long id;

	private String name;

	public Long getId() {
		return id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
}
