package models;

import javax.persistence.*;

@Entity
@Inheritance(strategy = InheritanceType.TABLE_PER_CLASS)
public class AbstractEntity {

	@SuppressWarnings("UnusedDeclaration") //generated by hibernate
	@Id
	@SequenceGenerator(name = "ppt_seq", sequenceName = "ppt_seq")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "ppt_seq")
	private Long id;

	public Long getId() {
		return id;
	}
}
