package models.ppt;

import javax.persistence.*;

@Entity
@Table(name = "ppt")
public class ProjectPlanningTool {
	@SuppressWarnings("UnusedDeclaration") //generated by hibernate
	@Id
	@SequenceGenerator(name = "ppt_seq", sequenceName = "ppt_seq")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "ppt_seq")
	private Long id;

	private String name;

	public Long getId() {
		return id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
}
